version: "3.9"

services:
  app:
    build: .
    container_name: tensorrt
    command: tail -f /dev/null
    volumes:
      - .:/app  # Mount current directory for live code updates (optional)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: "host"
    restart: unless-stopped
